# Generated by Django 4.2.9 on 2024-01-08 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_articlepost_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 2, 22, 16, 590168, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
