# Generated by Django 4.2.9 on 2024-01-08 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_alter_articlepost_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 3, 41, 57, 763979, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
