# Generated by Django 4.2.9 on 2024-01-08 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_articlepost_total_views_alter_articlepost_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 6, 27, 29, 657497, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
