# Generated by Django 4.2.9 on 2024-01-08 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_alter_articlepost_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 9, 8, 36, 444655, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="article.articlecolumn",
            ),
        ),
    ]
