# Generated by Django 4.2.9 on 2024-01-09 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0007_articlepost_tags_alter_articlepost_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="article/%Y%m%d"),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 3, 54, 14, 395747, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
