# Generated by Django 4.2.9 on 2024-01-09 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0008_articlepost_avatar_alter_articlepost_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 8, 6, 27, 954071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
