# Generated by Django 4.2.9 on 2024-01-10 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0010_alter_articlepost_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 10, 2, 0, 38, 712969, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
