# Generated by Django 4.2.9 on 2024-01-09 08:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
